openapi: 3.0.3
info:
    version: 1.0.0
    title: COAL Game Server
    description: An API for COAL Game Server
servers:
- url: /v1
paths:
  /game:
    get:
      summary: Retrieve a list of games
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfGames'
    post:
      summary: Create a new game
      requestBody:
          $ref: '#/components/requestBodies/GameBody'
      responses:
        '201':
          $ref: '#/components/responses/GameDetailResponse'
  /game/{game_id}:
    get:
      summary: Retrieve game details
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        '200':
          $ref: '#/components/responses/GameDetailResponse'
    put:
      summary: Update game parameters
      parameters:
        - $ref: '#/components/parameters/gameId'
      requestBody:
        $ref: '#/components/requestBodies/GameBody'
      responses:
        '200':
          $ref: '#/components/responses/GameDetailResponse'
    delete:
      summary: Remove game
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        '204':
          description: Game deleted
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    GameDetail:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
    GameSubmit:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    ArrayOfGames:
      type: array
      items:
        $ref: '#/components/schemas/Game'
  parameters:
    gameId:
      name: game_id
      in: path
      required: true
      description: The id of the game to edit
      schema:
        type: string
  requestBodies:
    GameBody:
      description: Settable Game properties
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameSubmit'
  responses:
    GameDetailResponse:
      description: Game detail
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameDetail'