openapi: 3.0.3
info:
    version: 1.0.0
    title: COAL Game Server
    description: An API for COAL Game Server
servers:
- url: /v1
paths:
  /game:
    get:
      summary: Retrieve a list of games
      responses:
        '200':
          $ref: '#/components/responses/GameListResponse'
    post:
      summary: Create a new game
      requestBody:
          $ref: '#/components/requestBodies/GameBody'
      responses:
        '201':
          $ref: '#/components/responses/GameDetailResponse'
  /game/{game_id}:
    get:
      summary: Retrieve game details
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        '200':
          $ref: '#/components/responses/GameDetailResponse'
    put:
      summary: Update game parameters
      parameters:
        - $ref: '#/components/parameters/gameId'
      requestBody:
        $ref: '#/components/requestBodies/GameBody'
      responses:
        '200':
          $ref: '#/components/responses/GameDetailResponse'
    delete:
      summary: Remove game
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        '204':
          description: Game deleted
  /game/{game_id}/character:
    post:
      summary: Create a new character in the game
      parameters:
        - $ref: '#/components/parameters/gameId'
      requestBody:
        $ref: '#/components/requestBodies/CharacterBody'
      responses:
        '201':
          $ref: '#/components/responses/CharacterDetailResponse'
  /game/{game_id}/character/{character_id}/turn:
    post:
      summary: Submit player turn
      parameters:
        - $ref: '#/components/parameters/gameId'
        - $ref: '#/components/parameters/characterId'
      requestBody:
        $ref: '#/components/requestBodies/TurnBody'
      responses:
        '201':
          $ref: '#/components/responses/TurnDetailResponse'
  /game/{game_id}/event:
    get:
      summary: Retrieve a list of events
      parameters:
        - $ref: '#/components/parameters/gameId'
      responses:
        '200':
          $ref: '#/components/responses/EventListResponse'
    post:
      summary: Create a new event
      parameters:
        - $ref: '#/components/parameters/gameId'
      requestBody:
        $ref: '#/components/requestBodies/EventBody'
      responses:
        '201':
          $ref: '#/components/responses/EventDetailResponse'
  /game/{game_id}/event/{event_id}:
    get:
      summary: Retrieve event details
      parameters:
        - $ref: '#/components/parameters/gameId'
        - $ref: '#/components/parameters/eventId'
      responses:
        '200':
          $ref: '#/components/responses/EventDetailResponse'
    put:
      summary: Update event parameters
      parameters:
        - $ref: '#/components/parameters/gameId'
        - $ref: '#/components/parameters/eventId'
      requestBody:
        $ref: '#/components/requestBodies/EventBody'
      responses:
        '200':
          $ref: '#/components/responses/EventDetailResponse'
    delete:
      summary: Remove event
      parameters:
        - $ref: '#/components/parameters/gameId'
        - $ref: '#/components/parameters/eventId'
      responses:
        '204':
          description: Event deleted
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    GameDetail:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    GameSubmit:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    ArrayOfGames:
      type: array
      items:
        $ref: '#/components/schemas/Game'
    CharacterSubmit:
      type: object
      properties:
        player_id:
          type: string
        title:
          type: string
    CharacterDetail:
      type: object
      properties:
        id:
          type: string
        game_id:
          type: string
        player_id:
          type: string
        title:
          type: string
        location:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string          
    TurnResponseStatus:
      type: string
      enum:
        - OK
        - ERROR
    TurnDetail:
      type: object
      properties:
        status: 
          $ref: '#/components/schemas/TurnResponseStatus'
        text:
          type: string
    TurnSubmit:
      type: object
      properties:
        command:
          type: string
    EventItem:
      type: object
      properties:
        id:
          type: string
        primitive:
          type: string
        arguments:
          type: array
          items:
            type: string
    EventItemList:
      type: array
      items:
        $ref: '#/components/schemas/EventItem'
    Event:
      type: object
      properties:
        id:
          type: string
        command:
          type: string
        conditions:
          $ref: '#/components/schemas/EventItemList'
        true_part:
          $ref: '#/components/schemas/EventItemList'
        false_part:
          $ref: '#/components/schemas/EventItemList'
    ArrayOfEvents:
      type: array
      items:
        $ref: '#/components/schemas/Event'
    EventItemSubmit:
      type: object
      properties:
        primitive:
          type: string
        arguments:
          type: array
          items:
            type: string
    EventItemSubmitList:
      type: array
      items:
        $ref: '#/components/schemas/EventItemSubmit'
    EventSubmit:
      type: object
      properties:
        command:
          type: string
        conditions:
          $ref: '#/components/schemas/EventItemSubmitList'
        true_part:
          $ref: '#/components/schemas/EventItemSubmitList'
        false_part:
          $ref: '#/components/schemas/EventItemSubmitList'
  parameters:
    gameId:
      name: game_id
      in: path
      required: true
      description: Game ID
      schema:
        type: string
    characterId:
      name: character_id
      in: path
      required: true
      description: Player Character ID
      schema:
        type: string
    eventId:
      name: event_id
      in: path
      required: true
      description: Event ID
      schema:
        type: string
  requestBodies:
    GameBody:
      description: Settable Game properties
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameSubmit'
    CharacterBody:
      description: Settable Player Character properties
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CharacterSubmit'
    TurnBody:
      description: Turn submission
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TurnSubmit'
    EventBody:
      description: Turn submission
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EventSubmit'
  responses:
    GameListResponse:
      description: List of games
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArrayOfGames'
    GameDetailResponse:
      description: Game detail
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameDetail'
    CharacterDetailResponse:
      description: Character detail
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CharacterDetail'
    TurnDetailResponse:
      description: Turn submission response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TurnDetail'
    EventListResponse:
      description: List of events
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArrayOfEvents'
    EventDetailResponse:
      description: Event detail
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Event'
