openapi: 3.0.3
info:
    version: 1.0.0
    title: COAL Player Server
    description: An API for players and their characters
servers:
- url: /v1
tags:
- name: player
- name: character
paths:
  /player:
    $ref: './resources/players.yaml'
  /player/{player_id}:
    $ref: './resources/player.yaml'
  /player/{player_id}/character:
    $ref: './resources/player-characters.yaml'
  /player/{player_id}/character/{character_id}:
    $ref: './resources/player-character.yaml'
  /character/{character_id}:
    $ref: './resources/character.yaml'
components:
  schemas:
    $ref: './schemas/_index.yaml'
  parameters:
    $ref: './parameters/_index.yaml'
  requestBodies:
    $ref: './requestBodies/_index.yaml'
  responses:
    $ref: './responses/_index.yaml'
