openapi: 3.0.3
info:
    version: 1.0.0
    title: Concurrent Online Adventure Land
    description: An API for playing multi-user text adventures
servers:
- url: /v1
tags:
  - name: game
  - name: room
  - name: turn
  - name: item
  - name: event
  - name: player
  - name: character
  - name: location
paths:
  /game/{game_id}/character/{character_id}/turn:
    $ref: './resources/game-character-turns.yaml'
  /game:
    $ref: './resources/games.yaml'
  /game/{game_id}:
    $ref: './resources/game.yaml'
  /game/{game_id}/room:
    $ref: './resources/game-rooms.yaml'
  /game/{game_id}/room/{room_id}:
    $ref: './resources/game-room.yaml'
  /game/{game_id}/item:
    $ref: './resources/game-items.yaml'
  /game/{game_id}/item/{item_id}:
    $ref: './resources/game-item.yaml'
  /game/{game_id}/event:
    $ref: './resources/game-events.yaml'
  /game/{game_id}/event/{event_id}:
    $ref: './resources/game-event.yaml'
  /game/{game_id}/player/{player_id}/character:
    $ref: './resources/game-player-characters.yaml'
  /game/{game_id}/location:
    $ref: './resources/game-locations.yaml'
  /game/{game_id}/location/{location_id}:
    $ref: './resources/game-location.yaml'
  /player:
    $ref: './resources/players.yaml'
  /player/{player_id}:
    $ref: './resources/player.yaml'
  /player/{player_id}/character:
    $ref: './resources/player-characters.yaml'
  /player/{player_id}/character/{character_id}:
    $ref: './resources/player-character.yaml'
components:
  schemas:
    $ref: './schemas/_index.yaml'
  parameters:
    $ref: './parameters/_index.yaml'
  requestBodies:
    $ref: './requestBodies/_index.yaml'
  responses:
    $ref: './responses/_index.yaml'
