openapi: 3.0.3
info:
    version: 1.0.0
    title: COAL Game Server
    description: An API for COAL Game Server
servers:
- url: /v1
paths:
  /game:
    get:
      summary: Retrieve a list of games
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfGames'
    post:
      summary: Create a new game
      requestBody:
          $ref: '#/components/requestBodies/GameBody'
      responses:
        '201':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Badly-formed request
        '500':
          description: Server error
  /game/{id}:
    put:
      summary: Update game parameters
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the game to edit
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/GameBody'
      responses:
        '200':
          description: Updated game
    delete:
      summary: Remove game
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the game to remove
          schema:
            type: string
      responses:
        '201':
          description: Game deleted
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
    ArrayOfGames:
      type: array
      items:
        $ref: '#/components/schemas/Game'
  requestBodies:
    GameBody:
      description: New Game
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'
    UpdateGame:
      description: Update Game
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'