openapi: 3.0.3
info:
    version: 1.0.0
    title: Concurrent Online Adventure Land, or MUD
    description: An API for playing multi-user text adventures
paths:
  /turn/{game}/{player}:
    post:
      summary: Submit player turn
      parameters:
        - name: game
          in: path
          required: true
          description: The id of the game
          schema:
            type: string
        - name: player
          in: path
          required: true
          description: The id of the player
          schema:
            type: string
      requestBody:
        description: Command text for server to process
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameTurnSubmission'
      responses:
        '200':
          description: Turn submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameTurnResponse'
        '404':
          description: Cannot find game or player in game
        '400':
          description: Badly-formed request
        '500':
          description: Server error
  /game:
    get:
      summary: Retrieve a list of games
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfGames'
    post:
      summary: Create a new game
      requestBody:
          $ref: '#/components/requestBodies/GameBody'
      responses:
        '200':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Badly-formed request
        '500':
          description: Server error
  /game/{id}:
    put:
      summary: Update game parameters
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the game to edit
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/GameBody'
      responses:
        '200':
          description: Updated game
components:
  schemas:
    TurnResponseStatus:
      type: string
      enum:
        - OK
        - ERROR
    GameTurnResponse:
      type: object
      properties:
        status: 
          $ref: '#/components/schemas/TurnResponseStatus'
        text:
          type: string
    GameTurnSubmission:
      type: object
      properties:
        command:
          type: string
    Game:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
    ArrayOfGames:
      type: array
      items:
        $ref: '#/components/schemas/Game'
  requestBodies:
    GameBody:
      description: New Game
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'
    UpdateGame:
      description: Update Game
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'